### ISSUE TITLE
MaskTransformation doesn't resize well

### ISSUE THREAD

**Issue by kuuuurt** [Commit451/coil-transformations#1]
I'm using your `MaskTransformation` however it doesn't resize according to my ImageView. I think it's resizing based on the image size.

**Comment by xanscale** [comment]
https://github.com/coil-kt/coil/issues/1888

i think should be updated from my MaskCropTransformation

@Commit451Bot

**Comment by Jawnnypoo** [comment]
@xanscale feel free to make a PR for this!
