### ISSUE TITLE
Missing build file `transformations-2.0.1.aar`

### ISSUE THREAD

**Issue by kaarlolahtela** [Commit451/coil-transformations#11]
when including
implementation("com.github.Commit451.coil-transformations:transformations:2.0.1")

Missing build file: https://jitpack.io/com/github/Commit451/coil-transformations/transformations/2.0.1/transformations-2.0.1.aar -- you have "debug" and "release" versions of that, but not without.

the implementation("com.github.Commit451.coil-transformations:transformations:1.1.2") works

**Comment by Jawnnypoo** [comment]
Good catch! Released 2.0.2 with a fix for this.
