### ISSUE TITLE
CropTransformation not cropping

### ISSUE THREAD

**Issue by mensarb** [Commit451/coil-transformations#15]
hi,

i just tested the crop transformation and i get the same result for type top, center and bottom. also nothing gets cropped
![image](https://github.com/Commit451/coil-transformations/assets/7085596/53f05bc7-f4e5-483a-b967-2ecbb01f31d3)

i apply them like this
`
binding.image.load(url){transformations(CropTransformation(CropTransformation.CropType.TOP))
}
`

coil version is 2.5.0
lib version is 2.0.2

lg

**Comment by YaminMahdi** [comment]
same here

**Comment by bonepeople** [comment]
I have fixed the issue and make a PullRequest

You can temporarily use `implementation("com.github.bonepeople.coil-transformations:transformations:2.0.3")` instead of the original dependencies before the PR is merged.

**Comment by Jawnnypoo** [comment]
Thanks! pushed 2.0.3
