### ISSUE TITLE
Transformations from base library and GPU library don't load

### ISSUE THREAD

**Issue by billyjoker** [Commit451/coil-transformations#2]
Hi, i can apply transformations that are already supported in Coil itself well, but when i try to load from the base library (transformations) and from GPU library the picture is not loaded

```
                    image.load("url_pic") {
                        transformations(VignetteFilterTransformation(applicationContext))
                    }
```

Tested with Android 6.0.1

**Comment by Jawnnypoo** [comment]
I tried this with the sample app and everything seems fine. Can you try the sample app with your device which isn't working and see if it works?

**Comment by billyjoker** [comment]
**SOLVED**: finally i've got the solution: it works when i changed the way to import the libraries, as belows (in addition to your documentation about adding jitpack):

```
    api("com.github.Commit451.coil-transformations:transformations:0.0.4")
    api("com.github.Commit451.coil-transformations:transformations-gpu:0.0.4")
```
I had the same but with `implementation`. It seems to work with `api `in order to have the library exposed transitive

**Comment by Jawnnypoo** [comment]
Is this added to the `build.gradle` of an Application module, or a library module? If it is an application module, `implementation` should work just fine. But nonetheless, glad you solved it!
