### ISSUE TITLE
Adding BlurTransformation that was removed in Coil 2.0

### ISSUE THREAD

**Issue by Nek-12** [Commit451/coil-transformations#8]
Coil 2.0 alpha has BlurTransformation [removed](https://coil-kt.github.io/coil/changelog/#200-alpha01-october-11-2021) from the library. 
The authors recommend copy-pasting source code to the project for those who relied on it, however BlurTransformation used deprecated APIs and internal methods heavily, many of which were removed, essentially making this advice impossible to follow.

It would be nice to have this library add an updated version of BlurTransformation and GrayscaleTransformation to help those who relied on them before.

**Comment by Jawnnypoo** [comment]
Good call, I can do this!

**Comment by Jawnnypoo** [comment]
This is done in 1.1.2. Enjoy!
